version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - /app/__pycache__
    networks:
      - opensearch-net
    env_file:
      - .env
    depends_on:
      - nginx
      - redis
      - postgres
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
  
  ollama1:
    image: ollama/ollama:latest
    container_name: ollama1
    ports:
      - "11434:11434"
    networks:
      - opensearch-net
    volumes:
      - ollama_data1:/root/.ollama
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama2:
    image: ollama/ollama:latest
    container_name: ollama2
    ports:
      - "11435:11434"
    networks:
      - opensearch-net
    volumes:
      - ollama_data2:/root/.ollama
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama3:
    image: ollama/ollama:latest
    container_name: ollama3
    ports:
      - "11436:11434"
    networks:
      - opensearch-net
    volumes:
      - ollama_data3:/root/.ollama
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  ollama4:
    image: ollama/ollama:latest
    container_name: ollama4
    ports:
      - "11437:11434"
    networks:
      - opensearch-net
    volumes:
      - ollama_data4:/root/.ollama
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  ollama5:
    image: ollama/ollama:latest
    container_name: ollama5
    ports:
      - "11438:11434"
    networks:
      - opensearch-net  
    volumes:
      - ollama_data5:/root/.ollama
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3    
  ollama6:
    image: ollama/ollama:latest
    container_name: ollama6
    ports:
      - "11439:11434"
    networks:
      - opensearch-net                  
    volumes:
      - ollama_data6:/root/.ollama
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3  
  ollama7:
    image: ollama/ollama:latest
    container_name: ollama7
    ports:
      - "11440:11434"
    networks:
      - opensearch-net
    volumes:
      - ollama_data7:/root/.ollama
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - opensearch-net
    restart: always
    depends_on:
      - ollama1
      - ollama2
      - ollama3
      - ollama4
      - ollama5
      - ollama6
      - ollama7
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6310:6379"
    networks:
      - opensearch-net
    volumes:
      - redis_data:/data
  
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=123456789#heleN
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - '5601'
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    networks:
      - opensearch-net
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=helen*1
    ports:
      - "5432:5432"
    networks:
      - opensearch-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  opensearch-net:
    driver: bridge

volumes:
  opensearch-data1:
  redis_data:
  postgres_data:
  ollama_data1:
  ollama_data2:
  ollama_data3:
  ollama_data4:
  ollama_data5:
  ollama_data6:
  ollama_data7:
  nginx_logs: