services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - /app/__pycache__
    networks:
      - opensearch-net
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6310:6379"
    networks:
      - opensearch-net
    volumes:
      - redis_data:/data
  
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=123456789#heleN
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - '5601'
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    networks:
      - opensearch-net
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=helen*1
    ports:
      - "5432:5432"
    networks:
      - opensearch-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  opensearch-net:

volumes:
  opensearch-data1:
  redis_data:
  postgres_data:
